name: Releases

on:
  push:
    tags:
      - "*"

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Gradle Build
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: assembleRelease

      - name: Rename Apks
        run: |
          mv app/build/outputs/apk/release/app-universal-release.apk EhViewer-NekoInverter-${{ github.ref_name }}-universal.apk
          mv app/build/outputs/apk/release/app-arm64-v8a-release.apk EhViewer-NekoInverter-${{ github.ref_name }}-arm64-v8a.apk
          mv app/build/outputs/apk/release/app-armeabi-v7a-release.apk EhViewer-NekoInverter-${{ github.ref_name }}-armeabi-v7a.apk
          mv app/build/outputs/apk/release/app-x86_64-release.apk EhViewer-NekoInverter-${{ github.ref_name }}-x86_64.apk
          mv app/build/outputs/apk/release/app-x86-release.apk EhViewer-NekoInverter-${{ github.ref_name }}-x86.apk
          mv app/build/outputs/mapping/release/mapping.txt EhViewer-NekoInverter-${{ github.ref_name }}-mapping.txt

      - name: Releases
        uses: softprops/action-gh-release@v2
        with:
          body: Bump Version
          files: |
            EhViewer-NekoInverter-${{ github.ref_name }}-universal.apk
            EhViewer-NekoInverter-${{ github.ref_name }}-arm64-v8a.apk
            EhViewer-NekoInverter-${{ github.ref_name }}-armeabi-v7a.apk
            EhViewer-NekoInverter-${{ github.ref_name }}-x86_64.apk
            EhViewer-NekoInverter-${{ github.ref_name }}-x86.apk
            EhViewer-NekoInverter-${{ github.ref_name }}-mapping.txt
